# Build binary
FROM golang:1.11 as builder

WORKDIR /usr/src/myapp

COPY ["go.mod", "go.sum", "healthcheck.sh", "main.go", "./"]
RUN go mod download

COPY "app" "./app/"
RUN CGO_ENABLED=0 GOOS=linux GO111MODULE=on go build -a -installsuffix cgo -o app-server .

# Create image
FROM alpine:latest

LABEL MAINTAINER="Lechuck Roh <lechuckroh@gmail.com>"

WORKDIR /app
RUN mkdir -p /app

RUN apk add --update curl && rm -rf /var/cache/apk/*

VOLUME ["/app/logs"]

EXPOSE 8080

HEALTHCHECK CMD /app/healthcheck.sh

COPY --from=builder /usr/src/myapp/app-server ./
COPY healthcheck.sh ./

ENTRYPOINT ["./app-server"]
